app {

  debug = true # Toggle verification printout

  # Change this to the full, absolute path to your MSRCorpus
  corpusPath = "./MSRCorpus"

  # This is where we will save the Delta tables
  tablePath = "./target/delta-tables"

  chunker {
      size = 1000   # Max characters per chunk
      overlap = 100 # Characters to overlap between chunks
    }
  embedding {
    model = "mxbai-embed-large"
    version = "1.3.0"
    ollamaHost = "http://localhost:11434"

  }
}